# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

In [3]:
Z = np.zeros(100)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [4]:
Z = np.ones(100)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [5]:
Z = np.full(100, 3)
print(Z)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [7]:
A = np.arange(9).reshape(3,3)
A[[0,1]] = A[[1,0]]
print(A)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 5. Создать вектор со значениями от 10 до 100

In [8]:
Z = np.arange(10,100)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [9]:
Z = np.arange(16).reshape(4,4)
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [10]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [11]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.17475025 0.4822926  0.21160369]
  [0.61076671 0.80092461 0.78013816]
  [0.11153191 0.26779815 0.90922333]]

 [[0.73548323 0.85432979 0.77196651]
  [0.78460803 0.96770732 0.71437619]
  [0.45892243 0.66615513 0.3435146 ]]

 [[0.4085495  0.66645965 0.46386073]
  [0.4947133  0.0914714  0.03181017]
  [0.73533689 0.86305502 0.64369489]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [14]:
Z = np.random.random((10,10))
print(Z)

[[0.85350311 0.92210297 0.55502392 0.91133488 0.65518842 0.92172026
  0.8898247  0.42236111 0.43252985 0.85709911]
 [0.07201497 0.22122124 0.94090231 0.66172986 0.63759194 0.42303285
  0.95798762 0.8716661  0.643879   0.73258959]
 [0.06974855 0.51048628 0.42913046 0.60818068 0.22060143 0.35064535
  0.51435517 0.73900519 0.85436586 0.12166489]
 [0.13038781 0.38029367 0.42949566 0.06457422 0.68581714 0.1136724
  0.74860179 0.72665444 0.69156663 0.32891219]
 [0.97693068 0.37905563 0.45063039 0.280224   0.60294034 0.1899101
  0.56674388 0.38292703 0.1935103  0.39034804]
 [0.79613937 0.45165913 0.63013669 0.01519604 0.36346276 0.46978209
  0.08151388 0.85632399 0.93290281 0.40481979]
 [0.12013406 0.62702053 0.28275146 0.11588572 0.15956331 0.1573198
  0.03793467 0.40388996 0.87283802 0.38725299]
 [0.75833941 0.57965987 0.87581289 0.15788925 0.80821554 0.49381315
  0.14864348 0.62857529 0.28932936 0.61114151]
 [0.20547889 0.92105703 0.46425134 0.00627087 0.33198527 0.42839339
  0.12283481 0.

In [15]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00627086983942271 0.9983552797084746


#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [17]:
Z = np.random.random(30)
print(Z)

[0.96699454 0.79281402 0.97359376 0.9885017  0.27868223 0.62036123
 0.89084719 0.88147128 0.54094127 0.24852132 0.23685617 0.89427538
 0.33528727 0.5046165  0.06958224 0.12209164 0.02795347 0.74714946
 0.47719606 0.98251246 0.72525877 0.91643543 0.5053461  0.0717316
 0.58481168 0.71633472 0.79976773 0.07437071 0.97492294 0.37801049]


In [18]:
m = Z.mean()
print(m)

0.5775746449902235


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [19]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [20]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [28]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[[ 0  1  2]
 [ 3 -4 -5]
 [-6 -7 -8]]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [30]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [33]:
Z = np.eye(2)
print(Z)

[[1. 0.]
 [0. 1.]]


In [39]:
Y = Z - Z.mean(axis=1, keepdims=True)
print(Y)

[[ 0.5 -0.5]
 [-0.5  0.5]]
